### PR TITLE
VFS implementation

### PR DESCRIPTION
**Pull request by omnit3a**
Implemented `vfs_register_fs` syscall and began work on `vfs_mount_fs`.

### CODE REVIEW

**Review by untodesu — APPROVED** [review]
seems legit

**Comment by omnit3a** [comment]
It appears you forget to merge the PR?

**Comment by omnit3a** [comment]
Drafted this PR because I'm currently working on it again

**Comment by untodesu** [comment]
Okay, just, you know, do the whole vfs thing and then mark it ready to merge alright?

**Comment by untodesu** [comment]
So there isn't that much of commit fragmentation

**Comment by untodesu** [comment]
Fair enough, the file hierarchy is now under heavy mutations

**Pull request closed without merging**
